<a href="https://colab.research.google.com/github/shohdy-source/Machine-Learing-Deep-Learning-/blob/main/RE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

Saving 969140360237.explainer.xml to 969140360237.explainer.xml
User uploaded file "969140360237.explainer.xml" with length 32649 bytes

In [3]:
import xml.etree.ElementTree as ET
import pandas as pd

xml_data = open('969140360237.explainer.xml', 'r').read()  # Read file
root = ET.XML(xml_data)  # Parse XML

data = []
cols = []
for i, child in enumerate(root):
    data.append([subchild.text for subchild in child])
    cols.append(child.tag)

df = pd.DataFrame(data).T  # Write in DF and transpose it
df.columns = cols  # Update column names
print(df)

   title  ...                                               body
0   None  ...  In this explainer, we will learn how to solve ...
1   None  ...                                   Recall that the
2   None  ...                                           \n
3   None  ...  Let us also recap how to plot the graph of an ...
4   None  ...                                               None
5   None  ...  Then, we can plot the coordinates on the Carte...
6   None  ...                                               None
7   None  ...  Being able to apply the definition of the abso...
8   None  ...  Let us now introduce the concept of absolute v...
9   None  ...                             Consider the equation
10  None  ...  Before we look at this algebraically, it can o...
11  None  ...                                               None
12  None  ...                                               None
13  None  ...  From this graph, we can see that the two lines...
14  None  ...                                               None
15  None  ...                  So, the solution to the equation
16  None  ...  Now, we can also see from the graph how we mig...
17  None  ...                                                As
18  None  ...                          We start with\n
19  None  ...                      Then, we look at \n
20  None  ...  Combining these two equations, we can see that...
21  None  ...  An alternative algebraic method, as opposed to...
22  None  ...                                  In this example,
23  None  ...  Subtracting 1 from both sides of both equation...
24  None  ...          This method can be summarized as follows.
25  None  ...                                           \n
26  None  ...  The two methods are equivalent, and while we c...
27  None  ...  We will now solve a variety of absolute value ...
28  None  ...                                           \n
29  None  ...                                           \n
30  None  ...  The remaining examples in this explainer will ...
31  None  ...                                           \n
32  None  ...                                           \n
33  None  ...                                           \n
34  None  ...                                           \n
35  None  ...                                           \n
36  None  ...  We will finish this explainer by recapping som...
37  None  ...                                           \n

[38 rows x 7 columns]

In [4]:
df

   title  ...                                               body
0   None  ...  In this explainer, we will learn how to solve ...
1   None  ...                                   Recall that the
2   None  ...                                           \n
3   None  ...  Let us also recap how to plot the graph of an ...
4   None  ...                                               None
5   None  ...  Then, we can plot the coordinates on the Carte...
6   None  ...                                               None
7   None  ...  Being able to apply the definition of the abso...
8   None  ...  Let us now introduce the concept of absolute v...
9   None  ...                             Consider the equation
10  None  ...  Before we look at this algebraically, it can o...
11  None  ...                                               None
12  None  ...                                               None
13  None  ...  From this graph, we can see that the two lines...
14  None  ...                                               None
15  None  ...                  So, the solution to the equation
16  None  ...  Now, we can also see from the graph how we mig...
17  None  ...                                                As
18  None  ...                          We start with\n
19  None  ...                      Then, we look at \n
20  None  ...  Combining these two equations, we can see that...
21  None  ...  An alternative algebraic method, as opposed to...
22  None  ...                                  In this example,
23  None  ...  Subtracting 1 from both sides of both equation...
24  None  ...          This method can be summarized as follows.
25  None  ...                                           \n
26  None  ...  The two methods are equivalent, and while we c...
27  None  ...  We will now solve a variety of absolute value ...
28  None  ...                                           \n
29  None  ...                                           \n
30  None  ...  The remaining examples in this explainer will ...
31  None  ...                                           \n
32  None  ...                                           \n
33  None  ...                                           \n
34  None  ...                                           \n
35  None  ...                                           \n
36  None  ...  We will finish this explainer by recapping som...
37  None  ...                                           \n

[38 rows x 7 columns]

In [5]:
f=df[['title', 'seo_meta_description', 'source_id', 'developer_name']]

In [6]:
f

   title seo_meta_description source_id developer_name
0   None                 None      None           None
1   None                 None      None           None
2   None                 None      None           None
3   None                 None      None           None
4   None                 None      None           None
5   None                 None      None           None
6   None                 None      None           None
7   None                 None      None           None
8   None                 None      None           None
9   None                 None      None           None
10  None                 None      None           None
11  None                 None      None           None
12  None                 None      None           None
13  None                 None      None           None
14  None                 None      None           None
15  None                 None      None           None
16  None                 None      None           None
17  None                 None      None           None
18  None                 None      None           None
19  None                 None      None           None
20  None                 None      None           None
21  None                 None      None           None
22  None                 None      None           None
23  None                 None      None           None
24  None                 None      None           None
25  None                 None      None           None
26  None                 None      None           None
27  None                 None      None           None
28  None                 None      None           None
29  None                 None      None           None
30  None                 None      None           None
31  None                 None      None           None
32  None                 None      None           None
33  None                 None      None           None
34  None                 None      None           None
35  None                 None      None           None
36  None                 None      None           None
37  None                 None      None           None

In [7]:
f=f.rename(columns={'title':'explainer id/name'})

In [ ]:
f

   explainer id/name seo_meta_description source_id developer_name
0               None                 None      None           None
1               None                 None      None           None
2               None                 None      None           None
3               None                 None      None           None
4               None                 None      None           None
5               None                 None      None           None
6               None                 None      None           None
7               None                 None      None           None
8               None                 None      None           None
9               None                 None      None           None
10              None                 None      None           None
11              None                 None      None           None
12              None                 None      None           None
13              None                 None      None           None
14              None                 None      None           None
15              None                 None      None           None
16              None                 None      None           None
17              None                 None      None           None
18              None                 None      None           None
19              None                 None      None           None
20              None                 None      None           None
21              None                 None      None           None
22              None                 None      None           None
23              None                 None      None           None
24              None                 None      None           None
25              None                 None      None           None
26              None                 None      None           None
27              None                 None      None           None
28              None                 None      None           None
29              None                 None      None           None
30              None                 None      None           None
31              None                 None      None           None
32              None                 None      None           None
33              None                 None      None           None
34              None                 None      None           None
35              None                 None      None           None
36              None                 None      None           None
37              None                 None      None           None

In [ ]:

print (list(df.columns))

['title', 'seo_meta_description', 'source_id', 'developer_name', 'developer_email', 'dictionary', 'body']

In [ ]:
df[['source_id']]

   source_id
0       None
1       None
2       None
3       None
4       None
5       None
6       None
7       None
8       None
9       None
10      None
11      None
12      None
13      None
14      None
15      None
16      None
17      None
18      None
19      None
20      None
21      None
22      None
23      None
24      None
25      None
26      None
27      None
28      None
29      None
30      None
31      None
32      None
33      None
34      None
35      None
36      None
37      None

In [ ]:
df[['seo_meta_description']]

   seo_meta_description
0                  None
1                  None
2                  None
3                  None
4                  None
5                  None
6                  None
7                  None
8                  None
9                  None
10                 None
11                 None
12                 None
13                 None
14                 None
15                 None
16                 None
17                 None
18                 None
19                 None
20                 None
21                 None
22                 None
23                 None
24                 None
25                 None
26                 None
27                 None
28                 None
29                 None
30                 None
31                 None
32                 None
33                 None
34                 None
35                 None
36                 None
37                 None

In [ ]:
df[['seo_meta_description']]

   seo_meta_description
0                  None
1                  None
2                  None
3                  None
4                  None
5                  None
6                  None
7                  None
8                  None
9                  None
10                 None
11                 None
12                 None
13                 None
14                 None
15                 None
16                 None
17                 None
18                 None
19                 None
20                 None
21                 None
22                 None
23                 None
24                 None
25                 None
26                 None
27                 None
28                 None
29                 None
30                 None
31                 None
32                 None
33                 None
34                 None
35                 None
36                 None
37                 None

In [ ]:
df[['developer_name']]

   developer_name
0            None
1            None
2            None
3            None
4            None
5            None
6            None
7            None
8            None
9            None
10           None
11           None
12           None
13           None
14           None
15           None
16           None
17           None
18           None
19           None
20           None
21           None
22           None
23           None
24           None
25           None
26           None
27           None
28           None
29           None
30           None
31           None
32           None
33           None
34           None
35           None
36           None
37           None

In [ ]:
df[['title']]

   title
0   None
1   None
2   None
3   None
4   None
5   None
6   None
7   None
8   None
9   None
10  None
11  None
12  None
13  None
14  None
15  None
16  None
17  None
18  None
19  None
20  None
21  None
22  None
23  None
24  None
25  None
26  None
27  None
28  None
29  None
30  None
31  None
32  None
33  None
34  None
35  None
36  None
37  None

In [8]:
from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

Saving 972198025105.explainer.xml to 972198025105.explainer.xml
User uploaded file "972198025105.explainer.xml" with length 22937 bytes

In [9]:
import xml.etree.ElementTree as ET
import pandas as pd

xml_data = open('972198025105.explainer.xml', 'r').read()  # Read file
root = ET.XML(xml_data)  # Parse XML

data = []
cols = []
for i, child in enumerate(root):
    data.append([subchild.text for subchild in child])
    cols.append(child.tag)

df1 = pd.DataFrame(data).T  # Write in DF and transpose it
df1.columns = cols  # Update column names
print(df1)

   title  ...                                               body
0   None  ...  In this explainer, we will learn how to identi...
1   None  ...  Fundamental physical quantities (also called b...
2   None  ...  The following is a list of the SI base quantit...
3   None  ...  In this explainer, we will only be considering...
4   None  ...  The explainer is specifically concerned with h...
5   None  ...  Length is measured using an instrument that is...
6   None  ...  A ruler is a straight-edged stick with graduat...
7   None  ...          The marks on a ruler are usually \n
8   None  ...
9   None  ...  The maximum length that can be measured by a r...
10  None  ...           To measure lengths of less than \n
11  None  ...
12  None  ...  The length measured by a vernier caliper is th...
13  None  ...
14  None  ...  The red arrow between the jaws of the caliper ...
15  None  ...  The main scale of the caliper is the same as t...
16  None  ...  Close inspection of the main scale of the cali...
17  None  ...  The following figure shows where the main scal...
18  None  ...
19  None  ...  The vernier scale consists of 10 marks. Each m...
20  None  ...  The best aligned mark corresponds to a value b...
21  None  ...  Let us now look at an example in which a verni...
22  None  ...                                           \n
23  None  ...  Another length-measuring device that can measu...
24  None  ...  Perhaps unhelpfully, the name of this instrume...
25  None  ...  The following figure shows a micrometer and th...
26  None  ...
27  None  ...  The object that the length of is to be measure...
28  None  ...  When the thimble is turned, it moves along the...
29  None  ...  Let us now look at an example in which a \n   ...
30  None  ...                                           \n
31  None  ...  Let us now look at an example involving compar...
32  None  ...                                           \n
33  None  ...  Let us now look at an example that involves ot...
34  None  ...                                           \n
35  None  ...  Mass is an SI base quantity. Mass is often con...
36  None  ...   Measuring devices that give readings in \n
37  None  ...  Supposing that such a device was taken to the ...
38  None  ...  Tools that measure weight can be calibrated to...
39  None  ...  A tool that can measure weight is shown in the...
40  None  ...
41  None  ...  The action of the weight of a measured object ...
42  None  ...  Another such tool is shown in the following fi...
43  None  ...
44  None  ...  For a pan balance, two weights act, one on eac...
45  None  ...  Let us now look at an example involving such t...
46  None  ...                                           \n
47  None  ...  Let us now summarize what has been learned in ...
48  None  ...                                           \n

[49 rows x 6 columns]

In [10]:
df1

   title  ...                                               body
0   None  ...  In this explainer, we will learn how to identi...
1   None  ...  Fundamental physical quantities (also called b...
2   None  ...  The following is a list of the SI base quantit...
3   None  ...  In this explainer, we will only be considering...
4   None  ...  The explainer is specifically concerned with h...
5   None  ...  Length is measured using an instrument that is...
6   None  ...  A ruler is a straight-edged stick with graduat...
7   None  ...          The marks on a ruler are usually \n
8   None  ...
9   None  ...  The maximum length that can be measured by a r...
10  None  ...           To measure lengths of less than \n
11  None  ...
12  None  ...  The length measured by a vernier caliper is th...
13  None  ...
14  None  ...  The red arrow between the jaws of the caliper ...
15  None  ...  The main scale of the caliper is the same as t...
16  None  ...  Close inspection of the main scale of the cali...
17  None  ...  The following figure shows where the main scal...
18  None  ...
19  None  ...  The vernier scale consists of 10 marks. Each m...
20  None  ...  The best aligned mark corresponds to a value b...
21  None  ...  Let us now look at an example in which a verni...
22  None  ...                                           \n
23  None  ...  Another length-measuring device that can measu...
24  None  ...  Perhaps unhelpfully, the name of this instrume...
25  None  ...  The following figure shows a micrometer and th...
26  None  ...
27  None  ...  The object that the length of is to be measure...
28  None  ...  When the thimble is turned, it moves along the...
29  None  ...  Let us now look at an example in which a \n   ...
30  None  ...                                           \n
31  None  ...  Let us now look at an example involving compar...
32  None  ...                                           \n
33  None  ...  Let us now look at an example that involves ot...
34  None  ...                                           \n
35  None  ...  Mass is an SI base quantity. Mass is often con...
36  None  ...   Measuring devices that give readings in \n
37  None  ...  Supposing that such a device was taken to the ...
38  None  ...  Tools that measure weight can be calibrated to...
39  None  ...  A tool that can measure weight is shown in the...
40  None  ...
41  None  ...  The action of the weight of a measured object ...
42  None  ...  Another such tool is shown in the following fi...
43  None  ...
44  None  ...  For a pan balance, two weights act, one on eac...
45  None  ...  Let us now look at an example involving such t...
46  None  ...                                           \n
47  None  ...  Let us now summarize what has been learned in ...
48  None  ...                                           \n

[49 rows x 6 columns]

In [11]:
    ##p = p.reindex(columns=['1Sun', '2Mon', '3Tue', '4Wed', '5Thu', '6Fri', '7Sat'])
f1=df1.reindex(columns=['title', 'seo_meta_description', 'source_id', 'developer_name'])

In [12]:
f1

   title seo_meta_description  source_id developer_name
0   None                 None        NaN           None
1   None                 None        NaN           None
2   None                 None        NaN           None
3   None                 None        NaN           None
4   None                 None        NaN           None
5   None                 None        NaN           None
6   None                 None        NaN           None
7   None                 None        NaN           None
8   None                 None        NaN           None
9   None                 None        NaN           None
10  None                 None        NaN           None
11  None                 None        NaN           None
12  None                 None        NaN           None
13  None                 None        NaN           None
14  None                 None        NaN           None
15  None                 None        NaN           None
16  None                 None        NaN           None
17  None                 None        NaN           None
18  None                 None        NaN           None
19  None                 None        NaN           None
20  None                 None        NaN           None
21  None                 None        NaN           None
22  None                 None        NaN           None
23  None                 None        NaN           None
24  None                 None        NaN           None
25  None                 None        NaN           None
26  None                 None        NaN           None
27  None                 None        NaN           None
28  None                 None        NaN           None
29  None                 None        NaN           None
30  None                 None        NaN           None
31  None                 None        NaN           None
32  None                 None        NaN           None
33  None                 None        NaN           None
34  None                 None        NaN           None
35  None                 None        NaN           None
36  None                 None        NaN           None
37  None                 None        NaN           None
38  None                 None        NaN           None
39  None                 None        NaN           None
40  None                 None        NaN           None
41  None                 None        NaN           None
42  None                 None        NaN           None
43  None                 None        NaN           None
44  None                 None        NaN           None
45  None                 None        NaN           None
46  None                 None        NaN           None
47  None                 None        NaN           None
48  None                 None        NaN           None

In [13]:
from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

Saving 973130769145.explainer.xml to 973130769145.explainer.xml
User uploaded file "973130769145.explainer.xml" with length 25523 bytes

In [15]:
import xml.etree.ElementTree as ET
import pandas as pd

xml_data = open('973130769145.explainer.xml', 'r').read()  # Read file
root = ET.XML(xml_data)  # Parse XML

data = []
cols = []
for i, child in enumerate(root):
    data.append([subchild.text for subchild in child])
    cols.append(child.tag)

df2 = pd.DataFrame(data).T  # Write in DF and transpose it
df2.columns = cols  # Update column names
print(df2)

   title  ...                                               body
0   None  ...  In this explainer, we will learn how to connec...
1   None  ...  The derivatives of a function give us many dif...
2   None  ...                     For a differentiable function
3   None  ...                                               None
4   None  ...  This is not the only information we can see fr...
5   None  ...                                               None
6   None  ...               This means we can analyze the curve
7   None  ...                                      We know when
8   None  ...  We can also do this with the second derivative...
9   None  ...                                           \n
10  None  ...                                   If our function
11  None  ...                                           \n
12  None  ...  The concavity of a curve may change at values of
13  None  ...                        Let’s start with the curve
14  None  ...                                               None
15  None  ...                                    When the curve
16  None  ...                                               None
17  None  ...  When the second derivative of our function swi...
18  None  ...                We can therefore use the graphs of
19  None  ...                                           \n
20  None  ...                           It is worth noting that
21  None  ...  In fact, some literature always includes endpo...
22  None  ...  Of course, finding increasing and decreasing i...
23  None  ...                                           \n
24  None  ...  We have also seen how to use the first derivat...
25  None  ...                                               None
26  None  ...  We can mark the local extrema as shown, and we...
27  None  ...                                               None
28  None  ...  At a local maximum of a differentiable functio...
29  None  ...                                           \n
30  None  ...  So far, in all of our examples, we have been g...
31  None  ...                                           \n
32  None  ...  Let’s now see an example where we want to dete...
33  None  ...                                           \n
34  None  ...  Let us finish by recapping some of the main po...
35  None  ...                                           \n
36  None  ...                                               None

[37 rows x 7 columns]

In [16]:
df2

   title  ...                                               body
0   None  ...  In this explainer, we will learn how to connec...
1   None  ...  The derivatives of a function give us many dif...
2   None  ...                     For a differentiable function
3   None  ...                                               None
4   None  ...  This is not the only information we can see fr...
5   None  ...                                               None
6   None  ...               This means we can analyze the curve
7   None  ...                                      We know when
8   None  ...  We can also do this with the second derivative...
9   None  ...                                           \n
10  None  ...                                   If our function
11  None  ...                                           \n
12  None  ...  The concavity of a curve may change at values of
13  None  ...                        Let’s start with the curve
14  None  ...                                               None
15  None  ...                                    When the curve
16  None  ...                                               None
17  None  ...  When the second derivative of our function swi...
18  None  ...                We can therefore use the graphs of
19  None  ...                                           \n
20  None  ...                           It is worth noting that
21  None  ...  In fact, some literature always includes endpo...
22  None  ...  Of course, finding increasing and decreasing i...
23  None  ...                                           \n
24  None  ...  We have also seen how to use the first derivat...
25  None  ...                                               None
26  None  ...  We can mark the local extrema as shown, and we...
27  None  ...                                               None
28  None  ...  At a local maximum of a differentiable functio...
29  None  ...                                           \n
30  None  ...  So far, in all of our examples, we have been g...
31  None  ...                                           \n
32  None  ...  Let’s now see an example where we want to dete...
33  None  ...                                           \n
34  None  ...  Let us finish by recapping some of the main po...
35  None  ...                                           \n
36  None  ...                                               None

[37 rows x 7 columns]

In [17]:
f2=df2.reindex(columns=['title', 'seo_meta_description', 'source_id', 'developer_name'])

In [18]:
f2

   title seo_meta_description source_id developer_name
0   None                 None      None           None
1   None                 None      None           None
2   None                 None      None           None
3   None                 None      None           None
4   None                 None      None           None
5   None                 None      None           None
6   None                 None      None           None
7   None                 None      None           None
8   None                 None      None           None
9   None                 None      None           None
10  None                 None      None           None
11  None                 None      None           None
12  None                 None      None           None
13  None                 None      None           None
14  None                 None      None           None
15  None                 None      None           None
16  None                 None      None           None
17  None                 None      None           None
18  None                 None      None           None
19  None                 None      None           None
20  None                 None      None           None
21  None                 None      None           None
22  None                 None      None           None
23  None                 None      None           None
24  None                 None      None           None
25  None                 None      None           None
26  None                 None      None           None
27  None                 None      None           None
28  None                 None      None           None
29  None                 None      None           None
30  None                 None      None           None
31  None                 None      None           None
32  None                 None      None           None
33  None                 None      None           None
34  None                 None      None           None
35  None                 None      None           None
36  None                 None      None           None

In [19]:
from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

Saving 973145156531.explainer.xml to 973145156531.explainer.xml
User uploaded file "973145156531.explainer.xml" with length 22774 bytes

In [20]:
import xml.etree.ElementTree as ET
import pandas as pd

xml_data = open('973145156531.explainer.xml', 'r').read()  # Read file
root = ET.XML(xml_data)  # Parse XML

data = []
cols = []
for i, child in enumerate(root):
    data.append([subchild.text for subchild in child])
    cols.append(child.tag)

df3 = pd.DataFrame(data).T  # Write in DF and transpose it
df3.columns = cols  # Update column names
print(df3)

   title  ...                                               body
0   None  ...  In this explainer, we will learn how to calcul...
1   None  ...  A geometric sequence is a sequence that has a ...
2   None  ...  For instance, the following sequence is geomet...
3   None  ...  This sequence has a common ratio of 3 since ea...
4   None  ...  If we define the first term in the general geo...
5   None  ...                We now notice that the exponent of
6   None  ...  Look at what happens when we divide a term by ...
7   None  ...  No matter which pair of terms we choose, their...
8   None  ...                             Let’s generalize this.
9   None  ...                                           \n
10  None  ...                                           \n
11  None  ...  Now, let’s go  back to our earlier example of ...
12  None  ...                We notice that as the term number,
13  None  ...  This is not always the case though. In fact, s...
14  None  ...  When an infinite geometric sequence has a fini...
15  None  ...  For instance, the following sequence has a com...
16  None  ...                                           \n
17  None  ...  To find a formula for the sum of the terms in ...
18  None  ...                      Multiplying this equation by
19  None  ...  We can now subtract the second equation from t...
20  None  ...           Dividing both sides of this equation by
21  None  ...  We stated earlier that for a convergent geomet...
22  None  ...                                This means that as
23  None  ...                                In other words, if
24  None  ...  We can consider what happens with our converge...
25  None  ...  This is sometimes called the sum to infinity o...
26  None  ...                                           \n
27  None  ...  Let’s now look at a question that requires us ...
28  None  ...                                           \n
29  None  ...  In our next example, we will see how to apply ...
30  None  ...                                           \n
31  None  ...  In our previous two examples, we established t...
32  None  ...                                           \n
33  None  ...  As previously mentioned, the application of th...
34  None  ...                                           \n
35  None  ...  Let’s now consider how this process would diff...
36  None  ...                                           \n
37  None  ...  In our next example, we will look at how to fi...
38  None  ...                                           \n
39  None  ...  In our final example, we look at how we can ap...
40  None  ...                                           \n
41  None  ...                                           \n

[42 rows x 6 columns]

In [21]:
df3

   title  ...                                               body
0   None  ...  In this explainer, we will learn how to calcul...
1   None  ...  A geometric sequence is a sequence that has a ...
2   None  ...  For instance, the following sequence is geomet...
3   None  ...  This sequence has a common ratio of 3 since ea...
4   None  ...  If we define the first term in the general geo...
5   None  ...                We now notice that the exponent of
6   None  ...  Look at what happens when we divide a term by ...
7   None  ...  No matter which pair of terms we choose, their...
8   None  ...                             Let’s generalize this.
9   None  ...                                           \n
10  None  ...                                           \n
11  None  ...  Now, let’s go  back to our earlier example of ...
12  None  ...                We notice that as the term number,
13  None  ...  This is not always the case though. In fact, s...
14  None  ...  When an infinite geometric sequence has a fini...
15  None  ...  For instance, the following sequence has a com...
16  None  ...                                           \n
17  None  ...  To find a formula for the sum of the terms in ...
18  None  ...                      Multiplying this equation by
19  None  ...  We can now subtract the second equation from t...
20  None  ...           Dividing both sides of this equation by
21  None  ...  We stated earlier that for a convergent geomet...
22  None  ...                                This means that as
23  None  ...                                In other words, if
24  None  ...  We can consider what happens with our converge...
25  None  ...  This is sometimes called the sum to infinity o...
26  None  ...                                           \n
27  None  ...  Let’s now look at a question that requires us ...
28  None  ...                                           \n
29  None  ...  In our next example, we will see how to apply ...
30  None  ...                                           \n
31  None  ...  In our previous two examples, we established t...
32  None  ...                                           \n
33  None  ...  As previously mentioned, the application of th...
34  None  ...                                           \n
35  None  ...  Let’s now consider how this process would diff...
36  None  ...                                           \n
37  None  ...  In our next example, we will look at how to fi...
38  None  ...                                           \n
39  None  ...  In our final example, we look at how we can ap...
40  None  ...                                           \n
41  None  ...                                           \n

[42 rows x 6 columns]

In [22]:
f3=df3.reindex(columns=['title', 'seo_meta_description', 'source_id', 'developer_name'])

In [23]:
f3

   title  seo_meta_description source_id developer_name
0   None                   NaN      None           None
1   None                   NaN      None           None
2   None                   NaN      None           None
3   None                   NaN      None           None
4   None                   NaN      None           None
5   None                   NaN      None           None
6   None                   NaN      None           None
7   None                   NaN      None           None
8   None                   NaN      None           None
9   None                   NaN      None           None
10  None                   NaN      None           None
11  None                   NaN      None           None
12  None                   NaN      None           None
13  None                   NaN      None           None
14  None                   NaN      None           None
15  None                   NaN      None           None
16  None                   NaN      None           None
17  None                   NaN      None           None
18  None                   NaN      None           None
19  None                   NaN      None           None
20  None                   NaN      None           None
21  None                   NaN      None           None
22  None                   NaN      None           None
23  None                   NaN      None           None
24  None                   NaN      None           None
25  None                   NaN      None           None
26  None                   NaN      None           None
27  None                   NaN      None           None
28  None                   NaN      None           None
29  None                   NaN      None           None
30  None                   NaN      None           None
31  None                   NaN      None           None
32  None                   NaN      None           None
33  None                   NaN      None           None
34  None                   NaN      None           None
35  None                   NaN      None           None
36  None                   NaN      None           None
37  None                   NaN      None           None
38  None                   NaN      None           None
39  None                   NaN      None           None
40  None                   NaN      None           None
41  None                   NaN      None           None

In [24]:
from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

Saving 974125905106.explainer.xml to 974125905106.explainer.xml
User uploaded file "974125905106.explainer.xml" with length 26602 bytes

In [26]:
import xml.etree.ElementTree as ET
import pandas as pd

xml_data = open('974125905106.explainer.xml', 'r').read()  # Read file
root = ET.XML(xml_data)  # Parse XML

data = []
cols = []
for i, child in enumerate(root):
    data.append([subchild.text for subchild in child])
    cols.append(child.tag)

df4 = pd.DataFrame(data).T  # Write in DF and transpose it
df4.columns = cols  # Update column names
print(df4)

   title  ...                                               body
0   None  ...  In this explainer, we will learn how to find g...
1   None  ...  In many cases, we associate the mean of two nu...
2   None  ...                                           \n
3   None  ...  We note that we cannot take the geometric mean...
4   None  ...                                              When
5   None  ...                                               None
6   None  ...           The rectangle on the left side has area
7   None  ...                 Thus, the square with side length
8   None  ...  We can also understand the geometric mean of t...
9   None  ...  When we draw a number line with these terms, w...
10  None  ...                                               None
11  None  ...  Taking the geometric mean of the first and thi...
12  None  ...  In other words, the second term of the geometr...
13  None  ...  Hence, the fourth term, 24, is the geometric m...
14  None  ...                                           \n
15  None  ...  In our first example, we will compute the geom...
16  None  ...                                           \n
17  None  ...  In the next example, we will find the geometri...
18  None  ...                                           \n
19  None  ...  We can also compute the geometric mean of more...
20  None  ...  Unlike the geometric mean of two numbers, the ...
21  None  ...                                                If
22  None  ...                                               None
23  None  ...  The rectangular box on the left side has the v...
24  None  ...      Hence, the rectangular box with side lengths
25  None  ...                                           \n
26  None  ...  Let us consider an example where we compute th...
27  None  ...                                           \n
28  None  ...  In previous examples, we considered the geomet...
29  None  ...                                           \n
30  None  ...                                   We can see that
31  None  ...  Let us find geometric means between a pair of ...
32  None  ...                                           \n
33  None  ...  In the previous example, we identified geometr...
34  None  ...  For instance, consider the geometric sequence ...
35  None  ...    In the next example, we will find all possible
36  None  ...                                           \n
37  None  ...  In our last example, we will identify the numb...
38  None  ...                                           \n
39  None  ...  Let us finish by recapping a few important con...
40  None  ...                                           \n

[41 rows x 7 columns]

In [27]:
df4

   title  ...                                               body
0   None  ...  In this explainer, we will learn how to find g...
1   None  ...  In many cases, we associate the mean of two nu...
2   None  ...                                           \n
3   None  ...  We note that we cannot take the geometric mean...
4   None  ...                                              When
5   None  ...                                               None
6   None  ...           The rectangle on the left side has area
7   None  ...                 Thus, the square with side length
8   None  ...  We can also understand the geometric mean of t...
9   None  ...  When we draw a number line with these terms, w...
10  None  ...                                               None
11  None  ...  Taking the geometric mean of the first and thi...
12  None  ...  In other words, the second term of the geometr...
13  None  ...  Hence, the fourth term, 24, is the geometric m...
14  None  ...                                           \n
15  None  ...  In our first example, we will compute the geom...
16  None  ...                                           \n
17  None  ...  In the next example, we will find the geometri...
18  None  ...                                           \n
19  None  ...  We can also compute the geometric mean of more...
20  None  ...  Unlike the geometric mean of two numbers, the ...
21  None  ...                                                If
22  None  ...                                               None
23  None  ...  The rectangular box on the left side has the v...
24  None  ...      Hence, the rectangular box with side lengths
25  None  ...                                           \n
26  None  ...  Let us consider an example where we compute th...
27  None  ...                                           \n
28  None  ...  In previous examples, we considered the geomet...
29  None  ...                                           \n
30  None  ...                                   We can see that
31  None  ...  Let us find geometric means between a pair of ...
32  None  ...                                           \n
33  None  ...  In the previous example, we identified geometr...
34  None  ...  For instance, consider the geometric sequence ...
35  None  ...    In the next example, we will find all possible
36  None  ...                                           \n
37  None  ...  In our last example, we will identify the numb...
38  None  ...                                           \n
39  None  ...  Let us finish by recapping a few important con...
40  None  ...                                           \n

[41 rows x 7 columns]

In [28]:
f4=df4.reindex(columns=['title', 'seo_meta_description', 'source_id', 'developer_name'])

In [29]:
f4

   title seo_meta_description source_id developer_name
0   None                 None      None           None
1   None                 None      None           None
2   None                 None      None           None
3   None                 None      None           None
4   None                 None      None           None
5   None                 None      None           None
6   None                 None      None           None
7   None                 None      None           None
8   None                 None      None           None
9   None                 None      None           None
10  None                 None      None           None
11  None                 None      None           None
12  None                 None      None           None
13  None                 None      None           None
14  None                 None      None           None
15  None                 None      None           None
16  None                 None      None           None
17  None                 None      None           None
18  None                 None      None           None
19  None                 None      None           None
20  None                 None      None           None
21  None                 None      None           None
22  None                 None      None           None
23  None                 None      None           None
24  None                 None      None           None
25  None                 None      None           None
26  None                 None      None           None
27  None                 None      None           None
28  None                 None      None           None
29  None                 None      None           None
30  None                 None      None           None
31  None                 None      None           None
32  None                 None      None           None
33  None                 None      None           None
34  None                 None      None           None
35  None                 None      None           None
36  None                 None      None           None
37  None                 None      None           None
38  None                 None      None           None
39  None                 None      None           None
40  None                 None      None           None

In [30]:
from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

Saving 979165921053.explainer.xml to 979165921053.explainer.xml
User uploaded file "979165921053.explainer.xml" with length 27956 bytes

In [31]:
import xml.etree.ElementTree as ET
import pandas as pd

xml_data = open('979165921053.explainer.xml', 'r').read()  # Read file
root = ET.XML(xml_data)  # Parse XML

data = []
cols = []
for i, child in enumerate(root):
    data.append([subchild.text for subchild in child])
    cols.append(child.tag)

df5 = pd.DataFrame(data).T  # Write in DF and transpose it
df5.columns = cols  # Update column names
print(df5)

   title  ...                                               body
0   None  ...  In this explainer, we will learn how to constr...
1   None  ...  We can quantify the equilibrium that exists be...
2   None  ...                                           \n
3   None  ...  In its simplest form, the equilibrium constant...
4   None  ...  If we extend this to the general equation\n
5   None  ...  Remember that, in chemistry, we use square bra...
6   None  ...                        When writing equations for
7   None  ...  We can see that the concentration of nitrogen ...
8   None  ...                                           \n
9   None  ...                                           \n
10  None  ...  It is important to note that some questions ma...
11  None  ...                                           \n
12  None  ...  At higher levels, the discussion of a topic kn...
13  None  ...              However, in certain cases, units for
14  None  ...                            Given the equation for
15  None  ...                                           \n
16  None  ...                  In terms of actually calculating
17  None  ...  Let’s imagine that during the production of am...
18  None  ...                              So, the equation for
19  None  ...  If we substitute the correct numbers into the ...
20  None  ...                                  When calculating
21  None  ...  It may also be the case that all the values ne...
22  None  ...  Hydrogen sulfide can be decomposed by heat acc...
23  None  ...                                           \n
24  None  ...  In the first row of the table above, we put th...
25  None  ...                                           \n
26  None  ...  Next, we fill out the next two rows, “Change” ...
27  None  ...  We can consider the change in the reactants to...
28  None  ...                                  We are told that
29  None  ...                  From here, we can calculate that
30  None  ...                                           \n
31  None  ...  In the final row of the table, we use the volu...
32  None  ...           With this information, we can calculate
33  None  ...  It is also possible that a question may provid...
34  None  ...                                  In this example,
35  None  ...  Again, using the ICE method, the following tab...
36  None  ...                                           \n
37  None  ...    Now, we have the values to substitute into the
38  None  ...  Using the examples above, we can see how we ar...
39  None  ...                                   If the value of
40  None  ...                                           \n
41  None  ...                                           \n

[42 rows x 7 columns]

In [32]:
df5

   title  ...                                               body
0   None  ...  In this explainer, we will learn how to constr...
1   None  ...  We can quantify the equilibrium that exists be...
2   None  ...                                           \n
3   None  ...  In its simplest form, the equilibrium constant...
4   None  ...  If we extend this to the general equation\n
5   None  ...  Remember that, in chemistry, we use square bra...
6   None  ...                        When writing equations for
7   None  ...  We can see that the concentration of nitrogen ...
8   None  ...                                           \n
9   None  ...                                           \n
10  None  ...  It is important to note that some questions ma...
11  None  ...                                           \n
12  None  ...  At higher levels, the discussion of a topic kn...
13  None  ...              However, in certain cases, units for
14  None  ...                            Given the equation for
15  None  ...                                           \n
16  None  ...                  In terms of actually calculating
17  None  ...  Let’s imagine that during the production of am...
18  None  ...                              So, the equation for
19  None  ...  If we substitute the correct numbers into the ...
20  None  ...                                  When calculating
21  None  ...  It may also be the case that all the values ne...
22  None  ...  Hydrogen sulfide can be decomposed by heat acc...
23  None  ...                                           \n
24  None  ...  In the first row of the table above, we put th...
25  None  ...                                           \n
26  None  ...  Next, we fill out the next two rows, “Change” ...
27  None  ...  We can consider the change in the reactants to...
28  None  ...                                  We are told that
29  None  ...                  From here, we can calculate that
30  None  ...                                           \n
31  None  ...  In the final row of the table, we use the volu...
32  None  ...           With this information, we can calculate
33  None  ...  It is also possible that a question may provid...
34  None  ...                                  In this example,
35  None  ...  Again, using the ICE method, the following tab...
36  None  ...                                           \n
37  None  ...    Now, we have the values to substitute into the
38  None  ...  Using the examples above, we can see how we ar...
39  None  ...                                   If the value of
40  None  ...                                           \n
41  None  ...                                           \n

[42 rows x 7 columns]

In [33]:
f5=df5.reindex(columns=['title', 'seo_meta_description', 'source_id', 'developer_name'])

In [34]:
f5

   title seo_meta_description source_id developer_name
0   None                 None      None           None
1   None                 None      None           None
2   None                 None      None           None
3   None                 None      None           None
4   None                 None      None           None
5   None                 None      None           None
6   None                 None      None           None
7   None                 None      None           None
8   None                 None      None           None
9   None                 None      None           None
10  None                 None      None           None
11  None                 None      None           None
12  None                 None      None           None
13  None                 None      None           None
14  None                 None      None           None
15  None                 None      None           None
16  None                 None      None           None
17  None                 None      None           None
18  None                 None      None           None
19  None                 None      None           None
20  None                 None      None           None
21  None                 None      None           None
22  None                 None      None           None
23  None                 None      None           None
24  None                 None      None           None
25  None                 None      None           None
26  None                 None      None           None
27  None                 None      None           None
28  None                 None      None           None
29  None                 None      None           None
30  None                 None      None           None
31  None                 None      None           None
32  None                 None      None           None
33  None                 None      None           None
34  None                 None      None           None
35  None                 None      None           None
36  None                 None      None           None
37  None                 None      None           None
38  None                 None      None           None
39  None                 None      None           None
40  None                 None      None           None
41  None                 None      None           None

In [35]:
from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

Saving 980162532502.explainer.xml to 980162532502.explainer.xml
User uploaded file "980162532502.explainer.xml" with length 34159 bytes

In [36]:
import xml.etree.ElementTree as ET
import pandas as pd

xml_data = open('980162532502.explainer.xml', 'r').read()  # Read file
root = ET.XML(xml_data)  # Parse XML

data = []
cols = []
for i, child in enumerate(root):
    data.append([subchild.text for subchild in child])
    cols.append(child.tag)

df6 = pd.DataFrame(data).T  # Write in DF and transpose it
df6.columns = cols  # Update column names
print(df6)

   title  ...                                               body
0   None  ...  In this explainer, we will learn how to define...
1   None  ...  The composition of a molecule can be expressed...
2   None  ...                                           \n
3   None  ...  The ratio of carbon atoms to hydrogen atoms to...
4   None  ...                                           \n
5   None  ...  Empirical formulas are also used to represent ...
6   None  ...                                           \n
7   None  ...  We can easily determine the empirical formula ...
8   None  ...                                           \n
9   None  ...  It is possible for the empirical formula and m...
10  None  ...  Empirical formulas are often derived from expe...
11  None  ...                                           \n
12  None  ...  Let us examine how to determine the empirical ...
13  None  ...      This gives us a ratio of carbon to oxygen of
14  None  ...  Decimal values that are close to whole numbers...
15  None  ...  In this example, we knew the mass of each elem...
16  None  ...  The complete process for determining the empir...
17  None  ...                                               None
18  None  ...                                           \n
19  None  ...  There will be occasions when solving for the e...
20  None  ...  In step 1, the mass of carbon, hydrogen, and o...
21  None  ...  We can multiply the entire ratio in the exampl...
22  None  ...                                           \n
23  None  ...  The chemical formula determined from the perce...
24  None  ...  Naphthalene is a compound containing carbon an...
25  None  ...  We can follow these steps to determine the mol...
26  None  ...  Then, we will divide the molar mass of the mol...
27  None  ...  We can multiply the subscripts in the empirica...
28  None  ...           The molecular formula of naphthalene is
29  None  ...                                               None
30  None  ...                                           \n
31  None  ...                                           \n
32  None  ...                                           \n
33  None  ...                                               None
34  None  ...                                               None
35  None  ...                                               None

[36 rows x 7 columns]

In [37]:
df6

   title  ...                                               body
0   None  ...  In this explainer, we will learn how to define...
1   None  ...  The composition of a molecule can be expressed...
2   None  ...                                           \n
3   None  ...  The ratio of carbon atoms to hydrogen atoms to...
4   None  ...                                           \n
5   None  ...  Empirical formulas are also used to represent ...
6   None  ...                                           \n
7   None  ...  We can easily determine the empirical formula ...
8   None  ...                                           \n
9   None  ...  It is possible for the empirical formula and m...
10  None  ...  Empirical formulas are often derived from expe...
11  None  ...                                           \n
12  None  ...  Let us examine how to determine the empirical ...
13  None  ...      This gives us a ratio of carbon to oxygen of
14  None  ...  Decimal values that are close to whole numbers...
15  None  ...  In this example, we knew the mass of each elem...
16  None  ...  The complete process for determining the empir...
17  None  ...                                               None
18  None  ...                                           \n
19  None  ...  There will be occasions when solving for the e...
20  None  ...  In step 1, the mass of carbon, hydrogen, and o...
21  None  ...  We can multiply the entire ratio in the exampl...
22  None  ...                                           \n
23  None  ...  The chemical formula determined from the perce...
24  None  ...  Naphthalene is a compound containing carbon an...
25  None  ...  We can follow these steps to determine the mol...
26  None  ...  Then, we will divide the molar mass of the mol...
27  None  ...  We can multiply the subscripts in the empirica...
28  None  ...           The molecular formula of naphthalene is
29  None  ...                                               None
30  None  ...                                           \n
31  None  ...                                           \n
32  None  ...                                           \n
33  None  ...                                               None
34  None  ...                                               None
35  None  ...                                               None

[36 rows x 7 columns]

In [38]:
f6=df6.reindex(columns=['title', 'seo_meta_description', 'source_id', 'developer_name'])

In [39]:
f6

   title seo_meta_description source_id developer_name
0   None                 None      None           None
1   None                 None      None           None
2   None                 None      None           None
3   None                 None      None           None
4   None                 None      None           None
5   None                 None      None           None
6   None                 None      None           None
7   None                 None      None           None
8   None                 None      None           None
9   None                 None      None           None
10  None                 None      None           None
11  None                 None      None           None
12  None                 None      None           None
13  None                 None      None           None
14  None                 None      None           None
15  None                 None      None           None
16  None                 None      None           None
17  None                 None      None           None
18  None                 None      None           None
19  None                 None      None           None
20  None                 None      None           None
21  None                 None      None           None
22  None                 None      None           None
23  None                 None      None           None
24  None                 None      None           None
25  None                 None      None           None
26  None                 None      None           None
27  None                 None      None           None
28  None                 None      None           None
29  None                 None      None           None
30  None                 None      None           None
31  None                 None      None           None
32  None                 None      None           None
33  None                 None      None           None
34  None                 None      None           None
35  None                 None      None           None

In [40]:
from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

Saving 985161036067.explainer.xml to 985161036067.explainer.xml
User uploaded file "985161036067.explainer.xml" with length 19996 bytes

In [41]:
import xml.etree.ElementTree as ET
import pandas as pd

xml_data = open('985161036067.explainer.xml', 'r').read()  # Read file
root = ET.XML(xml_data)  # Parse XML

data = []
cols = []
for i, child in enumerate(root):
    data.append([subchild.text for subchild in child])
    cols.append(child.tag)

df7 = pd.DataFrame(data).T  # Write in DF and transpose it
df7.columns = cols  # Update column names
print(df7)

   title  ...                                               body
0   None  ...  In this explainer, we will learn how to find t...
1   None  ...  The probability of an event is the likelihood ...
2   None  ...  When we discuss the likelihood of an event hap...
3   None  ...                                               None
4   None  ...  The sum of the probabilities of all possible o...
5   None  ...  In probability terms, a simple event refers to...
6   None  ...  We also need to consider “fairness” when discu...
7   None  ...                                           \n
8   None  ...  Consider the situation of flipping a fair coin...
9   None  ...                                           \n
10  None  ...  Commonly in probability, we may use the notation
11  None  ...  We can now see how this information can be app...
12  None  ...                                           \n
13  None  ...  In the following example, we will see how we m...
14  None  ...                                           \n
15  None  ...                       We consider another example.
16  None  ...                                           \n
17  None  ...  We will now look at an example where we are gi...
18  None  ...                                           \n
19  None  ...  We will now look at an example where we find t...
20  None  ...                                           \n
21  None  ...  In the final example, we will use a given prob...
22  None  ...                                           \n
23  None  ...                   We now summarize the key points.
24  None  ...                                           \n
25  None  ...                                               None
26  None  ...                                               None
27  None  ...                                               None
28  None  ...                                               None
29  None  ...                                               None
30  None  ...                                               None
31  None  ...                                               None
32  None  ...                                               None
33  None  ...                                               None
34  None  ...                                               None

[35 rows x 7 columns]

In [42]:
df7

   title  ...                                               body
0   None  ...  In this explainer, we will learn how to find t...
1   None  ...  The probability of an event is the likelihood ...
2   None  ...  When we discuss the likelihood of an event hap...
3   None  ...                                               None
4   None  ...  The sum of the probabilities of all possible o...
5   None  ...  In probability terms, a simple event refers to...
6   None  ...  We also need to consider “fairness” when discu...
7   None  ...                                           \n
8   None  ...  Consider the situation of flipping a fair coin...
9   None  ...                                           \n
10  None  ...  Commonly in probability, we may use the notation
11  None  ...  We can now see how this information can be app...
12  None  ...                                           \n
13  None  ...  In the following example, we will see how we m...
14  None  ...                                           \n
15  None  ...                       We consider another example.
16  None  ...                                           \n
17  None  ...  We will now look at an example where we are gi...
18  None  ...                                           \n
19  None  ...  We will now look at an example where we find t...
20  None  ...                                           \n
21  None  ...  In the final example, we will use a given prob...
22  None  ...                                           \n
23  None  ...                   We now summarize the key points.
24  None  ...                                           \n
25  None  ...                                               None
26  None  ...                                               None
27  None  ...                                               None
28  None  ...                                               None
29  None  ...                                               None
30  None  ...                                               None
31  None  ...                                               None
32  None  ...                                               None
33  None  ...                                               None
34  None  ...                                               None

[35 rows x 7 columns]

In [43]:
f7=df7.reindex(columns=['title', 'seo_meta_description', 'source_id', 'developer_name'])

In [44]:
f7

   title seo_meta_description source_id developer_name
0   None                 None      None           None
1   None                 None      None           None
2   None                 None      None           None
3   None                 None      None           None
4   None                 None      None           None
5   None                 None      None           None
6   None                 None      None           None
7   None                 None      None           None
8   None                 None      None           None
9   None                 None      None           None
10  None                 None      None           None
11  None                 None      None           None
12  None                 None      None           None
13  None                 None      None           None
14  None                 None      None           None
15  None                 None      None           None
16  None                 None      None           None
17  None                 None      None           None
18  None                 None      None           None
19  None                 None      None           None
20  None                 None      None           None
21  None                 None      None           None
22  None                 None      None           None
23  None                 None      None           None
24  None                 None      None           None
25  None                 None      None           None
26  None                 None      None           None
27  None                 None      None           None
28  None                 None      None           None
29  None                 None      None           None
30  None                 None      None           None
31  None                 None      None           None
32  None                 None      None           None
33  None                 None      None           None
34  None                 None      None           None

In [45]:
from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

Saving 985195836913.explainer.xml to 985195836913.explainer.xml
User uploaded file "985195836913.explainer.xml" with length 28418 bytes

In [46]:
import xml.etree.ElementTree as ET
import pandas as pd

xml_data = open('972198025105.explainer.xml', 'r').read()  # Read file
root = ET.XML(xml_data)  # Parse XML

data = []
cols = []
for i, child in enumerate(root):
    data.append([subchild.text for subchild in child])
    cols.append(child.tag)

df8 = pd.DataFrame(data).T  # Write in DF and transpose it
df8.columns = cols  # Update column names
print(df8)

   title  ...                                               body
0   None  ...  In this explainer, we will learn how to identi...
1   None  ...  Fundamental physical quantities (also called b...
2   None  ...  The following is a list of the SI base quantit...
3   None  ...  In this explainer, we will only be considering...
4   None  ...  The explainer is specifically concerned with h...
5   None  ...  Length is measured using an instrument that is...
6   None  ...  A ruler is a straight-edged stick with graduat...
7   None  ...          The marks on a ruler are usually \n
8   None  ...
9   None  ...  The maximum length that can be measured by a r...
10  None  ...           To measure lengths of less than \n
11  None  ...
12  None  ...  The length measured by a vernier caliper is th...
13  None  ...
14  None  ...  The red arrow between the jaws of the caliper ...
15  None  ...  The main scale of the caliper is the same as t...
16  None  ...  Close inspection of the main scale of the cali...
17  None  ...  The following figure shows where the main scal...
18  None  ...
19  None  ...  The vernier scale consists of 10 marks. Each m...
20  None  ...  The best aligned mark corresponds to a value b...
21  None  ...  Let us now look at an example in which a verni...
22  None  ...                                           \n
23  None  ...  Another length-measuring device that can measu...
24  None  ...  Perhaps unhelpfully, the name of this instrume...
25  None  ...  The following figure shows a micrometer and th...
26  None  ...
27  None  ...  The object that the length of is to be measure...
28  None  ...  When the thimble is turned, it moves along the...
29  None  ...  Let us now look at an example in which a \n   ...
30  None  ...                                           \n
31  None  ...  Let us now look at an example involving compar...
32  None  ...                                           \n
33  None  ...  Let us now look at an example that involves ot...
34  None  ...                                           \n
35  None  ...  Mass is an SI base quantity. Mass is often con...
36  None  ...   Measuring devices that give readings in \n
37  None  ...  Supposing that such a device was taken to the ...
38  None  ...  Tools that measure weight can be calibrated to...
39  None  ...  A tool that can measure weight is shown in the...
40  None  ...
41  None  ...  The action of the weight of a measured object ...
42  None  ...  Another such tool is shown in the following fi...
43  None  ...
44  None  ...  For a pan balance, two weights act, one on eac...
45  None  ...  Let us now look at an example involving such t...
46  None  ...                                           \n
47  None  ...  Let us now summarize what has been learned in ...
48  None  ...                                           \n

[49 rows x 6 columns]

In [47]:
df8

   title  ...                                               body
0   None  ...  In this explainer, we will learn how to identi...
1   None  ...  Fundamental physical quantities (also called b...
2   None  ...  The following is a list of the SI base quantit...
3   None  ...  In this explainer, we will only be considering...
4   None  ...  The explainer is specifically concerned with h...
5   None  ...  Length is measured using an instrument that is...
6   None  ...  A ruler is a straight-edged stick with graduat...
7   None  ...          The marks on a ruler are usually \n
8   None  ...
9   None  ...  The maximum length that can be measured by a r...
10  None  ...           To measure lengths of less than \n
11  None  ...
12  None  ...  The length measured by a vernier caliper is th...
13  None  ...
14  None  ...  The red arrow between the jaws of the caliper ...
15  None  ...  The main scale of the caliper is the same as t...
16  None  ...  Close inspection of the main scale of the cali...
17  None  ...  The following figure shows where the main scal...
18  None  ...
19  None  ...  The vernier scale consists of 10 marks. Each m...
20  None  ...  The best aligned mark corresponds to a value b...
21  None  ...  Let us now look at an example in which a verni...
22  None  ...                                           \n
23  None  ...  Another length-measuring device that can measu...
24  None  ...  Perhaps unhelpfully, the name of this instrume...
25  None  ...  The following figure shows a micrometer and th...
26  None  ...
27  None  ...  The object that the length of is to be measure...
28  None  ...  When the thimble is turned, it moves along the...
29  None  ...  Let us now look at an example in which a \n   ...
30  None  ...                                           \n
31  None  ...  Let us now look at an example involving compar...
32  None  ...                                           \n
33  None  ...  Let us now look at an example that involves ot...
34  None  ...                                           \n
35  None  ...  Mass is an SI base quantity. Mass is often con...
36  None  ...   Measuring devices that give readings in \n
37  None  ...  Supposing that such a device was taken to the ...
38  None  ...  Tools that measure weight can be calibrated to...
39  None  ...  A tool that can measure weight is shown in the...
40  None  ...
41  None  ...  The action of the weight of a measured object ...
42  None  ...  Another such tool is shown in the following fi...
43  None  ...
44  None  ...  For a pan balance, two weights act, one on eac...
45  None  ...  Let us now look at an example involving such t...
46  None  ...                                           \n
47  None  ...  Let us now summarize what has been learned in ...
48  None  ...                                           \n

[49 rows x 6 columns]

In [48]:
f8=df8.reindex(columns=['title', 'seo_meta_description', 'source_id', 'developer_name'])

In [49]:
f8

   title seo_meta_description  source_id developer_name
0   None                 None        NaN           None
1   None                 None        NaN           None
2   None                 None        NaN           None
3   None                 None        NaN           None
4   None                 None        NaN           None
5   None                 None        NaN           None
6   None                 None        NaN           None
7   None                 None        NaN           None
8   None                 None        NaN           None
9   None                 None        NaN           None
10  None                 None        NaN           None
11  None                 None        NaN           None
12  None                 None        NaN           None
13  None                 None        NaN           None
14  None                 None        NaN           None
15  None                 None        NaN           None
16  None                 None        NaN           None
17  None                 None        NaN           None
18  None                 None        NaN           None
19  None                 None        NaN           None
20  None                 None        NaN           None
21  None                 None        NaN           None
22  None                 None        NaN           None
23  None                 None        NaN           None
24  None                 None        NaN           None
25  None                 None        NaN           None
26  None                 None        NaN           None
27  None                 None        NaN           None
28  None                 None        NaN           None
29  None                 None        NaN           None
30  None                 None        NaN           None
31  None                 None        NaN           None
32  None                 None        NaN           None
33  None                 None        NaN           None
34  None                 None        NaN           None
35  None                 None        NaN           None
36  None                 None        NaN           None
37  None                 None        NaN           None
38  None                 None        NaN           None
39  None                 None        NaN           None
40  None                 None        NaN           None
41  None                 None        NaN           None
42  None                 None        NaN           None
43  None                 None        NaN           None
44  None                 None        NaN           None
45  None                 None        NaN           None
46  None                 None        NaN           None
47  None                 None        NaN           None
48  None                 None        NaN           None

In [50]:
from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

Saving 989130863985.explainer.xml to 989130863985.explainer.xml
User uploaded file "989130863985.explainer.xml" with length 24995 bytes

In [51]:
import xml.etree.ElementTree as ET
import pandas as pd

xml_data = open('989130863985.explainer.xml', 'r').read()  # Read file
root = ET.XML(xml_data)  # Parse XML

data = []
cols = []
for i, child in enumerate(root):
    data.append([subchild.text for subchild in child])
    cols.append(child.tag)

df9 = pd.DataFrame(data).T  # Write in DF and transpose it
df9.columns = cols  # Update column names
print(df9)

   title  ...                                               body
0   None  ...  In this explainer, we will learn how to calcul...
1   None  ...  Imagine an object that moves at a constant vel...
2   None  ...
3   None  ...  Since the velocity is constant, the graph show...
4   None  ...  The object in the graph above moves at a veloc...
5   None  ...  Another question we could ask is “What is the ...
6   None  ...  Now imagine an object that moves at a steadily...
7   None  ...
8   None  ...  Since the velocity is increasing steadily over...
9   None  ...             In this case, the initial velocity is
10  None  ...  But another way of thinking about this is in t...
11  None  ...
12  None  ...  The blue region is a rectangle, so its area is...
13  None  ...     Since we said that the velocity is increasing
14  None  ...                Let’s have a look at some examples.
15  None  ...                                           \n
16  None  ...                   So far, we have only considered
17  None  ...
18  None  ...  In this case, since the velocity is negative t...
19  None  ...  So we have now considered what we have to do i...
20  None  ...
21  None  ...                              The line crosses the
22  None  ...                                      In the first
23  None  ...              Let’s have a look at another example.
24  None  ...                                         \n
25  None  ...  So far, we have only looked at how we find the...
26  None  ...         However, if instead we wanted to find the
27  None  ...                                         \n
28  None  ...  When the line on a velocity–time graph is stra...
29  None  ...                                         \n
30  None  ...                                         \n
31  None  ...                                           \n

[32 rows x 6 columns]

In [52]:
df9

   title  ...                                               body
0   None  ...  In this explainer, we will learn how to calcul...
1   None  ...  Imagine an object that moves at a constant vel...
2   None  ...
3   None  ...  Since the velocity is constant, the graph show...
4   None  ...  The object in the graph above moves at a veloc...
5   None  ...  Another question we could ask is “What is the ...
6   None  ...  Now imagine an object that moves at a steadily...
7   None  ...
8   None  ...  Since the velocity is increasing steadily over...
9   None  ...             In this case, the initial velocity is
10  None  ...  But another way of thinking about this is in t...
11  None  ...
12  None  ...  The blue region is a rectangle, so its area is...
13  None  ...     Since we said that the velocity is increasing
14  None  ...                Let’s have a look at some examples.
15  None  ...                                           \n
16  None  ...                   So far, we have only considered
17  None  ...
18  None  ...  In this case, since the velocity is negative t...
19  None  ...  So we have now considered what we have to do i...
20  None  ...
21  None  ...                              The line crosses the
22  None  ...                                      In the first
23  None  ...              Let’s have a look at another example.
24  None  ...                                         \n
25  None  ...  So far, we have only looked at how we find the...
26  None  ...         However, if instead we wanted to find the
27  None  ...                                         \n
28  None  ...  When the line on a velocity–time graph is stra...
29  None  ...                                         \n
30  None  ...                                         \n
31  None  ...                                           \n

[32 rows x 6 columns]

In [53]:
f9=df9.reindex(columns=['title', 'seo_meta_description', 'source_id', 'developer_name'])

In [54]:
f9

   title seo_meta_description source_id  developer_name
0   None                 None      None             NaN
1   None                 None      None             NaN
2   None                 None      None             NaN
3   None                 None      None             NaN
4   None                 None      None             NaN
5   None                 None      None             NaN
6   None                 None      None             NaN
7   None                 None      None             NaN
8   None                 None      None             NaN
9   None                 None      None             NaN
10  None                 None      None             NaN
11  None                 None      None             NaN
12  None                 None      None             NaN
13  None                 None      None             NaN
14  None                 None      None             NaN
15  None                 None      None             NaN
16  None                 None      None             NaN
17  None                 None      None             NaN
18  None                 None      None             NaN
19  None                 None      None             NaN
20  None                 None      None             NaN
21  None                 None      None             NaN
22  None                 None      None             NaN
23  None                 None      None             NaN
24  None                 None      None             NaN
25  None                 None      None             NaN
26  None                 None      None             NaN
27  None                 None      None             NaN
28  None                 None      None             NaN
29  None                 None      None             NaN
30  None                 None      None             NaN
31  None                 None      None             NaN

**Concat DataFrames**

In [72]:
pdList = [f,f1,f2,f3,f4,f5,f6,f7,f8,f9]  # List of your dataframes
new_df = pd.concat(pdList)

In [73]:
new_df

   explainer id/name seo_meta_description source_id developer_name title
0               None                 None      None           None  None
1               None                 None      None           None  None
2               None                 None      None           None  None
3               None                 None      None           None  None
4               None                 None      None           None  None
..               ...                  ...       ...            ...   ...
27               NaN                  NaN       NaN            NaN   NaN
28               NaN                  NaN       NaN            NaN   NaN
29               NaN                  NaN       NaN            NaN   NaN
30               NaN                  NaN       NaN            NaN   NaN
31               NaN                  NaN       NaN            NaN   NaN

[401 rows x 5 columns]

In [80]:
new_df_1=new_df.drop('title',1)

In [81]:
new_df_1

   explainer id/name seo_meta_description source_id developer_name
0               None                 None      None           None
1               None                 None      None           None
2               None                 None      None           None
3               None                 None      None           None
4               None                 None      None           None
..               ...                  ...       ...            ...
27               NaN                  NaN       NaN            NaN
28               NaN                  NaN       NaN            NaN
29               NaN                  NaN       NaN            NaN
30               NaN                  NaN       NaN            NaN
31               NaN                  NaN       NaN            NaN

[401 rows x 4 columns]

In [82]:
new_df_1_t=new_df_1.T

In [83]:
new_df_1_t

                        0     1     2     3   ...    28    29    30    31
explainer id/name     None  None  None  None  ...   NaN   NaN   NaN   NaN
seo_meta_description  None  None  None  None  ...  None  None  None  None
source_id             None  None  None  None  ...  None  None  None  None
developer_name        None  None  None  None  ...   NaN   NaN   NaN   NaN

[4 rows x 401 columns]

In [71]:
new_df_T=new_df.drop(df.columns[[4]],axis=1)

KeyError: ignored

In [70]:
new_df_T

   explainer id/name seo_meta_description source_id explainer id/name
0               None                 None      None              None
1               None                 None      None              None
2               None                 None      None              None
3               None                 None      None              None
4               None                 None      None              None
..               ...                  ...       ...               ...
27               NaN                  NaN       NaN               NaN
28               NaN                  NaN       NaN               NaN
29               NaN                  NaN       NaN               NaN
30               NaN                  NaN       NaN               NaN
31               NaN                  NaN       NaN               NaN

[401 rows x 4 columns]

In [59]:
new_df_T

                                                                     0   ...        37
title                                                              None  ...      None
seo_meta_description                                               None  ...      None
source_id                                                          None  ...      None
developer_name                                                     None  ...      None
developer_email                                                    None  ...      None
dictionary                                                     \n        ...      None
body                  In this explainer, we will learn how to solve ...  ...  \n

[7 rows x 38 columns]